<a href="https://colab.research.google.com/github/farhanns481/notes/blob/main/numpyy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY



*   Python library used for working arrays.
*   numpy stands for numerical python

*   import numpy as np

   






In [ ]:
import numpy as np
x= np.array([12,14,23,45,104])
x

type(x)

numpy.ndarray

In [ ]:
x.shape #no of elements

(5,)

In [ ]:
x.ndim #dimention

1

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([
    [1,2,3],
    [9,8,7],
    [5,0,6]
])

In [ ]:
y

array([[1, 2, 3],
       [9, 8, 7],
       [5, 0, 6]])

In [ ]:
y.shape

(3, 3)

In [ ]:
y.size

9

In [ ]:
y = np.array([
    [1,2,3],
    [9,8,7],
    [5,0,6.0]
])

In [ ]:
y.dtype

dtype('float64')

In [ ]:
xy = np.array([1.5,2.3,4.6,7.5],dtype=np.int64)
xy

array([1, 2, 4, 7])

In [ ]:
xy + 3

array([ 4,  5,  7, 10])

In [ ]:
xy *2

array([ 2,  4,  8, 14])

In [ ]:
a1 = np.zeros((3,4),dtype=np.int64)
a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
a2 = np.ones((3,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a3 = np.eye(4)
a3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a4 = np.diag([100,21,-12,15])
a4

array([[100,   0,   0,   0],
       [  0,  21,   0,   0],
       [  0,   0, -12,   0],
       [  0,   0,   0,  15]])

In [ ]:
a5 = np.arange(10)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a6 = np.arange(10,25)
a6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a6.size

15

In [ ]:
len(a6)

15

In [ ]:
a6.shape

(15,)

In [ ]:
a7 = np.reshape(a6,(3,5))
a7

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
import random

a8 = np.random.random((4,3))
a8

array([[0.23104646, 0.68795132, 0.58626756],
       [0.93344305, 0.49086997, 0.28203519],
       [0.68441194, 0.58068635, 0.17791855],
       [0.31674578, 0.21956225, 0.8328268 ]])

In [ ]:
a9 = np.random.randint(10,25,size=(5,3))
a9

array([[11, 10, 10],
       [21, 19, 20],
       [22, 11, 16],
       [21, 24, 22],
       [17, 15, 10]])

In [ ]:
a9[0]

array([11, 10, 10])

In [ ]:
a9[-1]

array([17, 15, 10])

In [ ]:
a9[0:3]

array([[11, 10, 10],
       [21, 19, 20],
       [22, 11, 16]])

In [ ]:
a9[0,0]

np.int64(11)

In [ ]:
a9[0,-1]

np.int64(10)

In [ ]:
a9[0:3,0:2]

array([[11, 10],
       [21, 19],
       [22, 11]])

In [ ]:
a9[3:,1:]

array([[24, 22],
       [15, 10]])

In [ ]:
a0 = [1,6,5,20,13]
a1 = np.mean(a0)
a1

np.float64(9.0)

In [ ]:
a0 = [1,6,5,20,13]
a1 = np.median(a0)
a1

np.float64(6.0)

In [ ]:
q1=[5,4,3,2,6,1]
q2=np.sort(q1)
q2

array([1, 2, 3, 4, 5, 6])

In [ ]:
k1=[2,3,4,5,6,7]
k2=np.count_nonzero(k1)
k2

6

In [ ]:
w1=3.18
w2=np.round(w1)
w2

np.float64(3.0)

In [ ]:
Y = np.array([
    [1,2,3],
    [9,8,7],
    [5,6,7],
])
X =  np.array([
    [1,5,3],
    [9,0,7],
    [5,0,7],
])
xy = np.add(X,Y)
xy

array([[ 2,  7,  6],
       [18,  8, 14],
       [10,  6, 14]])

In [ ]:
Y = np.array([
    [1,2,3],
    [9,8,7],
    [5,6,7],
])
X =  np.array([
    [1,5,3],
    [9,0,7],
    [5,0,7],
])
xy = np.subtract(X,Y)
xy

array([[ 0,  3,  0],
       [ 0, -8,  0],
       [ 0, -6,  0]])

In [ ]:
kw = 64
kn=np.sqrt(kw)
kn

np.float64(8.0)

In [ ]:
#cocatenation
#transpose
#linspace
#full function
#index position of max values
#flatten
#multiplication
#access
#where
#percent
#cumulative
#standard deviation
#variant
#dot
#copy
#view



In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,np.nan,6,7])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    7.0
dtype: float64

In [ ]:
dp = pd.DataFrame(np.random.randint(0,100,size=(5,3)))
dp

0   1   2
0  31  93  90
1  71  65  72
2  93   2  63
3  48  20  38
4  57  39  64

In [ ]:
df = pd.DataFrame(np.random.randint(0,100,size=(5,3)),columns=['A','B','C'])
df

A   B   C
0  95   4  58
1  87  71  55
2  66  31  90
3  89   4  92
4  63  16  17

In [ ]:
data = {
    "calories":[400,500,600,700],
    "duration":[10,20,30,40]

  }
Sc = pd.DataFrame(data)
print(Sc)

   calories  duration
0       400        10
1       500        20
2       600        30
3       700        40


In [ ]:
Sc["calories"]

0    400
1    500
2    600
3    700
Name: calories, dtype: int64

In [ ]:
Sc.loc[1]

calories    500
duration     20
Name: 1, dtype: int64

In [ ]:
Sc.loc[0:3]

calories  duration
0       400        10
1       500        20
2       600        30
3       700        40

In [ ]:
data = {
    "calories":[400,500,600,700],
    "duration":[10,20,30,40]

  }
Sc = pd.DataFrame(data,index=['day1','day2','day3','day4'])
print(Sc)

      calories  duration
day1       400        10
day2       500        20
day3       600        30
day4       700        40


In [ ]:
Sc.iloc[0:5]

calories  duration
day1       400        10
day2       500        20
day3       600        30
day4       700        40

In [ ]:
Sc.reset_index(drop=True)

calories  duration
0       400        10
1       500        20
2       600        30
3       700        40

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1VdgNwORHh4HlimuuEgrsixRgko2Gi1YdnlUYAnkPFR8/export?format=csv&gid=0"
Sc = pd.read_csv(url)

In [ ]:
Sc = pd.read_csv("/content/data - Sheet1.csv")

In [ ]:
Sc.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
Sc.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
Sc.shape

(169, 4)

In [ ]:
Sc.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
Sc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
Sc.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
Sc.isna()

Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
..        ...    ...       ...       ...
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

[169 rows x 4 columns]

In [ ]:
Sc.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
Sc[Sc['Calories']<=100]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
93         15     80       100      50.5
100        20     95       112      77.7
104        30     92       108      92.7
107        30     90       120      86.2

In [ ]:
Sc[(Sc['Calories']<=100)&(Sc['Duration']==20)]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
100        20     95       112      77.7

In [ ]:
Sc.drop(165)

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
163        45    100       140     280.9
164        60    105       140     290.8
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[168 rows x 4 columns]

In [ ]:
Sc.drop(['Calories'],axis=1)

Duration  Pulse  Maxpulse
0          60    110       130
1          60    117       145
2          60    103       135
3          45    109       175
4          45    117       148
..        ...    ...       ...
164        60    105       140
165        60    110       145
166        60    115       145
167        75    120       150
168        75    125       150

[169 rows x 3 columns]

In [ ]:
Sc.nunique()

Duration     16
Pulse        47
Maxpulse     57
Calories    142
dtype: int64

In [ ]:
Sc['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
Sc['Duration'].value_counts()

Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
75      2
160     2
210     2
15      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [ ]:
Sc.groupby('Duration')['Calories'].mean()

Duration
15       87.350000
20      151.600000
25      244.200000
30      192.125000
45      273.236364
60      339.675000
75      325.400000
80      643.100000
90      541.800000
120     666.833333
150     939.400000
160     943.700000
180     733.600000
210    1618.200000
270    1729.000000
300    1500.200000
Name: Calories, dtype: float64

In [ ]:
Sc["Calories_per_min"] = Sc["Calories"]/Sc["Duration"]
Sc.head()

Duration  Pulse  Maxpulse  Calories  Calories_per_min
0        60    110       130     409.1          6.818333
1        60    117       145     479.0          7.983333
2        60    103       135     340.0          5.666667
3        45    109       175     282.4          6.275556
4        45    117       148     406.0          9.022222

In [ ]:
import seaborn as sns
data = sns.load_dataset('titanic')

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']